Nz = 128 * 2^3  #number of z-sites
Nd = 2
Nt = 32 * 2^4
Ny = 32 * 2^6

Z_range = (0.0, 10centi)
T_range = (0.0, 100micro)
Y_width = 10milli
Y_range = (-Y_width / 2, Y_width / 2)

seperation = 40micro
pulse_params = [
    ((center=T_range[2] / 2, width=10micro, area=1.0), (center=-seperation / 2, width=10micro, area=1.0e-6)),
    ((center=T_range[2] / 2, width=10micro, area=1.0), (center=seperation / 2, width=10micro, area=1.0e-6))
]